// samples/dino-game/interactive-demo-vue/src/components/DinoGame/DinoGame.vue
<script>
import DinoGameCore from './DinoGameCore.vue'
import { useFeatBitStore } from '@/featbit'

export default {
    components: {
        DinoGameCore
    },
    setup() {
        const featBitStore = useFeatBitStore();
        return {
            featBitStore
        }
    }
}
</script>

<style lang="less">
@import "./DinoGame.less";
</style>    
    
<template>
    <div class="dino-game-wrapper">
        <DinoGameCore v-if="featBitStore.flags['game-runner'] == true" />
        <div class="comingsoon-wrapper" v-if="featBitStore.flags['game-runner'] == false">
            <h1>Swith "game-runner" feature flag to ON to release Dino Game</h1>
        </div>
    </div>
</template>

// samples/dino-game/interactive-demo-react/src/features/dinoGame/DinoGame.js
import React, { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { DinoGameCore } from './DinoGameCore';
import './DinoGame.css';

export function DinoGame() {
    useEffect(() => {
    });
    return (
        <div className="dino-game-wrapper">
            <DinoGameCore />
            {/* <div className="comingsoon-wrapper" v-if="featBitStore.flags['game-runner'] == false">
                <h1>Swith "game-runner" feature flag to ON to release Dino Game</h1>
            </div> */}
        </div>
    );
}
